### ISSUE TITLE
Use pickle for inter-thread communications instead of crazy JSON bile

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/website-api#4]

**Comment by hhhorb** [comment]
Yes, +1.

**Comment by ghost** [comment]
Done in https://github.com/BunsenLabs/website-api/commit/1bed23ae9cacc2eda970786642f4a1cc17f75923, https://github.com/BunsenLabs/website-api/commit/6c9a561a7f7136d2d255066811f197cc6dd5e25d. Closing.
